name: Postman CI
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  postman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Postman Collection
        uses: postmanlabs/postman-cli-action@v1
        with:
          api-key: ${{ secrets.POSTMAN_API_KEY }}
          command: collection run 52238111-652f7fbd-5f9a-465e-bd25-7cdbde0bbc04 -e 52274286-f3a79803-6669-4b5b-919b-b83b54cacb8a --report-events --verbose
